# Generated by Django 5.1.6 on 2025-02-13 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Doctor', 'doctor'), ('Patient', 'patient')], default='Patient', max_length=100, null=True),
        ),
    ]
