# Generated by Django 5.1.6 on 2025-02-14 01:45

import packages.integerId
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_user_country_user_emergency_contact_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorassignment',
            name='id',
            field=packages.integerId.IntegerIDField(db_index=True, default=packages.integerId.uniqueID, editable=False, max_length=16, primary_key=True, serialize=False, unique=True),
        ),
    ]
