# Generated by Django 5.1.6 on 2025-02-14 03:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_doctornote_actionablestep_patientcheckin'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionablestep',
            name='completed_checklist',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_description', models.TextField()),
                ('scheduled_at', models.DateTimeField()),
                ('completed', models.BooleanField(default=False)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to=settings.AUTH_USER_MODEL)),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='authentication.actionablestep')),
            ],
        ),
    ]
